version: '3.8'

volumes:
  pgdata:
  tmp:
  opdata:
  bundle:

services:
  backend:
    image: openproject/dev:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/dev/backend/Dockerfile
      target: develop
      args:
        DEV_UID: ${DEV_UID:-1000}
        DEV_GID: ${DEV_GID:-1000}
    command: run-app
    depends_on:
      - db
      - cache
      - frontend
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_DATABASE:-openproject}?pool=100
      LOCAL_DEV_CHECK: "${LOCAL_DEV_CHECK:-1}"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
      OPENPROJECT_RAILS__CACHE__STORE: file_store
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      OPENPROJECT_SSRF_PROTECTION_IP_ALLOWLIST: 0.0.0.0/0,::0/0
      OPENPROJECT_WEB_MAX__THREADS: 1
      OPENPROJECT_WEB_MIN__THREADS: 1
      OPENPROJECT_WEB_WORKERS: 0
      PIDFILE: /home/dev/openproject/tmpfs/pids/server.pid
      RAILS_ENV: development
    volumes:
      - ".:/home/dev/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp:/home/dev/openproject/tmp"
    tmpfs:
      - /home/dev/openproject/tmpfs/pids:uid=1000,gid=1000
    ports:
      - "${PORT:-3000}:3000"

  worker:
    image: openproject/dev:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/dev/backend/Dockerfile
      target: develop
      args:
        DEV_UID: ${DEV_UID:-1000}
        DEV_GID: ${DEV_GID:-1000}
    command: bundle exec good_job start
    depends_on:
      - db
      - cache
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_DATABASE:-openproject}?pool=100
      LOCAL_DEV_CHECK: "${LOCAL_DEV_CHECK:-1}"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
      OPENPROJECT_RAILS__CACHE__STORE: file_store
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      OPENPROJECT_SSRF_PROTECTION_IP_ALLOWLIST: 0.0.0.0/0,::0/0
      OPENPROJECT_WEB_MAX__THREADS: 1
      OPENPROJECT_WEB_MIN__THREADS: 1
      OPENPROJECT_WEB_WORKERS: 0
      PIDFILE: /home/dev/openproject/tmpfs/pids/server.pid
      RAILS_ENV: development
    volumes:
      - ".:/home/dev/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp:/home/dev/openproject/tmp"
    tmpfs:
      - /home/dev/openproject/tmpfs/pids:uid=1000,gid=1000

  frontend:
    build:
      context: .
      dockerfile: ./docker/dev/frontend/Dockerfile
      args:
        DEV_UID: ${DEV_UID:-1000}
        DEV_GID: ${DEV_GID:-1000}
    command: "node --max_old_space_size=8096 ./node_modules/@angular/cli/bin/ng serve --host 0.0.0.0"
    volumes:
      - ".:/home/dev/openproject"
      - "${CKEDITOR_BUILD_DIR:-./frontend/src/vendor/ckeditor/}:/home/dev/openproject/frontend/src/vendor/ckeditor/"
    environment:
      __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "openproject-assets.${OPENPROJECT_DOCKER_DEV_TLD:-local}"
    ports:
      - "${FE_PORT:-4200}:4200"

  db:
    image: postgres:17
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-openproject}

  cache:
    image: memcached
    restart: unless-stopped